export const PAGE_LINK = {
  DETAIL_WELCOME: {NAME: '/welcome',PRIVATE:false},
  COVER_TYPE: {NAME: '/cover-type',PRIVATE:false},
  BUDGET_OFFER: {NAME: '/plan'},PRIVATE:true,
  CONTACT: {NAME: '/contact',PRIVATE:false},
  BUDGET_PER_EMP: {NAME: '/input',PRIVATE:true},
  BUSINESS_BRIEF_INFO: {NAME: '/business-brief-info',PRIVATE:false},
  BUSINESS_DETAIL: {NAME: '/business',PRIVATE:true},
  PERSON_DETAIL: {NAME: 'person',PRIVATE:false},
  EMPLOYEE_SECTION:{NAME: 'employee-section', BG:'WOMAN',PRIVATE:false},
  SELF_COMPLETE_EMP: {NAME: '/employee-diy',PRIVATE:true},
  SELF_COMPLETE_EMP_RESULT:{NAME: '/employee-diy-result',PRIVATE:true},
  EMPLOYEE_PROVIDER: {NAME: '/employee',PRIVATE:true},
  UPLOAD_FILE: {NAME: '/employer-upload',PRIVATE:true},
  UPLOAD_FILE_RESULT: {NAME: '/employer-upload-result',PRIVATE:true},
  PURCHASE_SUMMARY: {NAME: '/purchase-summary',PRIVATE:true},
  TERM_CONFIRMATION: {NAME: '/TnC',PRIVATE:true},
  QR_CONFIRMATION: {NAME: '/email-sent',PRIVATE:true},
  PAYMENT_TYPE:{NAME: '/payment',PRIVATE:true},
  PAYMENT_RESULT_SUCCESS:{NAME: '/payment-success',PRIVATE:true},
  PAYMENT_RESULT_FAILED:{NAME: '/payment-failed',PRIVATE:true},
  KYC_UPLOAD_SUCCESS:{NAME: '/KYC-Success',PRIVATE:true},
  CREDIT_PAYMENT:{NAME: '/payment-credit',PRIVATE:false},
  THANK_FOR_CHOOSING:{NAME: '/thank-for-choosing', BG:'WOMAN',PRIVATE:false},
  APOLOGIZE_NOT_ELIGIBLE:{NAME: '/apologize-not-eligible', BG:'WOMAN',PRIVATE:false},
  ACTIVITY_LEARN_MORE:{NAME: '/activity',PRIVATE:false},
  TERM_AND_CONDITION:{NAME: '/term-and-condition',PRIVATE:false},
  PERSON_DETAIL_INFO:{NAME: 'person-detail-info', BG:'WOMAN',PRIVATE:false},
  HEALTH_QUESTION: {NAME: 'health-question', BG:'WOMAN',PRIVATE:false},
  DIRECTOR_AUTHORIZATION: {NAME: '/authorization',PRIVATE:false},
  IDENTITY_VERIFICATION: {NAME: '/KYC',PRIVATE:false},
  FORBIDDEN_PAGE:{NAME: '/forbidden',PRIVATE:false},
  ERROR_PAGE:{NAME: '/error',PRIVATE:false},
  SILENT_RENEW:{NAME: '/silent-refresh',PRIVATE:false},
  SIGNIN:{NAME: '/signin-oidc',PRIVATE:false},
  LOGOUT:{NAME: '/logout',PRIVATE:false},
  LOGOUT_CALLBACK:{NAME: '/logout/callback',PRIVATE:false},
  AFFILIATE:{NAME:'/affiliate',PRIVATE:false},
  FORGOT_PASSWORD:{NAME:'/change-password',PRIVATE:false}
}
